service:
  name: dmi-aws-bootcamp-serverless

frameworkVersion: ">=1.0.0 <2.0.0"


provider:
  name: aws
  runtime: nodejs10.x
  environment: # Service wide environment variables
    TABLE_NAME: {Ref: petsTable} #butz-bootcamp-PetTable-19KKTKSJVLG8T
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::Join:
           - ""
           - - "arn:aws:dynamodb:${self:provider.region}:"
             - Ref: AWS::AccountId
             - ":table/"
             - {Ref: petsTable}

functions:
  createPet:
    handler: createPet.lambdaHandler
    layers:
      - {Ref: PetLayerLambdaLayer}
    events:
      - http:
          path: pet
          method: post
  readPet:
    handler: readPet.lambdaHandler
    layers:
      - {Ref: PetLayerLambdaLayer}
    events:
      - http:
          path: pet/{petId}
          method: get
          request:
            parameters:
              paths:
                petId: true
  updatePet:
    handler: updatePet.lambdaHandler
    layers:
      - {Ref: PetLayerLambdaLayer}
    events:
      - http:
          path: pet/{petId}
          method: put
          request:
            parameters:
              paths:
                petId: true
  deletePet:
    handler: deletePet.lambdaHandler
    layers:
      - {Ref: PetLayerLambdaLayer}
    events:
      - http:
          path: pet/{petId}
          method: delete
          request:
            parameters:
              paths:
                petId: true
  listPets:
    handler: listPets.lambdaHandler
    layers:
      - {Ref: PetLayerLambdaLayer}
    events:
      - http:
          path: pet
          method: get

layers:
  petLayer:
    path: petLayer
    compatibleRuntimes:
      - nodejs10.x

resources:
  Resources:
    petsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:
    ApiUrl:
      Description: The ARN for the User's Table
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: "ApiGatewayRestApi"
            - ".execute-api.${self:provider.region}."
            - Ref: "AWS::URLSuffix"
            - "/${self:provider.stage}"